export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
export const ADD_TO_WATCHLATER = "ADD_TO_WATCHLATER";
export const REMOVE_FROM_WATCHLATER = "REMOVE_FROM_WATCHLATER";
export const CREATE_NEW_PLAYLIST = "CREATE_NEW_PLAYLIST";
export const ADD_REMOVE_FROM_PLAYLIST = "ADD_REMOVE_FROM_PLAYLIST";

export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const CREDENTIALS_VERIFICATION_TRUE = "CREDENTIALS_VERIFICATION_TRUE";
export const CREDENTIALS_VERIFICATION_FALSE = "CREDENTIALS_VERIFICATION_FALSE";
